version: 0.2

phases:
  build:
    commands:
      - cd springboot/
      - echo Build started on `date`
      - echo Building the jar
      - mvn spring-javaformat:apply
      - mvn package
      - mv target/spring-petclinic-2.4.5.jar app.jar
artifacts:
  files:
    - app.jar