version: 0.2

phases:
  build:
    commands:
      - cd springboot/
      - echo Build started on `date`
      - echo Building the jar
      - mvn spring-javaformat:apply
      - mvn package
      - cd ..
      - mv springboot/target/spring-petclinic-2.4.5.jar application.jar
artifacts:
  files:
    - application.jar
cache:
  paths:
  - '/root/.m2/**/*'